name: ponte
version: '1.0-SNAPSHOT'
main: me.tunisiaa.ponte.Ponte
authors: [ TuNisiAa ]
description: Il mio primo plugin
api-version: 1.19
commands:
  tpa:
    description: Teletrasporto
    usage: /<command> <target player>
    permission: bukkit.broadcast
  tpaccept:
    description: Accettazione teletrasporto
    usage: /<command> <target player>
    permission: bukkit.broadcast